version: '3.5'

networks:
  default:
    name: nw_nats

services:
  sc_nats:
    image: nats:${NATS_VERSION}
    restart: unless-stopped
    container_name: ct_nats
    ports:
      - ${NATS_CLIENT_PORT}:4222
      - ${NATS_MONITOR_PORT}:8222
      - ${NATS_ROUTE_PORT}:6222
