version: '3.5'

networks:
  default:
    name: nw_pg

services:
  sc_pg:
    image: postgres
    restart: unless-stopped
    container_name: ct_pg
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data

  sc_pgadmin4:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: ct_pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
      - ${PGADMIN_XPORT}:443
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./admin:/var/lib/pgadmin
