version: '3.5'

networks:
  default:
    name: nw_mongo

services:
  fix-mongodb-permissions:
    image: bitnami/mongodb:${MONGODB_VERSION}
    user: root
    command: chown -R 1001:1001 /bitnami
    volumes:
    - ${MONGODB_PATH}:/bitnami

  sc_mongo:
    image: bitnami/mongodb:${MONGODB_VERSION}
    restart: unless-stopped
    container_name: ct_mongo
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      # - MONGODB_USERNAME=${MONGODB_USERNAME}
      # - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      # - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
     - ${MONGODB_PATH}:/bitnami
    depends_on:
    - fix-mongodb-permissions