# https://joaquimadraz.com/guide-to-deploy-an-elixir-phoenix-app-to-aws-ecs
version: "3"
# Need to run on ECS instance: `docker network create external-network`

networks:
  default:
    name: ${NETWORK_NAME}

services:
  es:
    image: elasticsearch:7.17.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  kibana:
    image: kibana:7.17.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200

    depends_on:
      - es
