FROM ubuntu:16.04

## step 1: update apt
RUN sudo apt-get update && sudo apt-get upgrade

## step 2: install necessary Python packages
RUN sudo apt-get install -y \
    python-dateutil \
    python-docutils \
    python-feedparser \
    python-jinja2 \
    python-ldap \
    python-libxslt1 \
    python-lxml \
    python-mako \
    python-mock \
    python-openid \
    python-psycopg2 \
    python-psutil \
    python-pybabel \
    python-pychart \
    python-pydot \
    python-pyparsing \
    python-reportlab \
    python-simplejson \
    python-tz \
    python-unittest2 \
    python-vatnumber \
    python-vobject \
    python-webdav \
    python-werkzeug \
    python-xlwt \
    python-yaml \
    python-zsi \
    poppler-utils \
    python-pip \
    python-pypdf \
    python-passlib \
    python-decorator \
    gcc \
    python-dev \
    mc \
    bzr \
    python-setuptools \
    python-markupsafe \
    python-reportlab-accel \
    python-zsi \
    python-yaml \
    python-argparse \
    python-openssl \
    python-egenix-mxdatetime \
    python-usb \
    python-serial \
    lptools \
    make \
    python-pydot \
    python-psutil \
    python-paramiko \
    poppler-utils \
    python-pdftools \
    antiword \
    python-requests \
    python-xlsxwriter \
    python-suds \
    python-psycogreen \
    python-ofxparse \
    python-gevent

## step 3: odoo web dependencies
RUN sudo apt-get install -y npm
RUN sudo ln -s /usr/bin/nodejs /usr/bin/node
RUN sudo npm install -g less less-plugin-clean-css

## step 4: install postgres
RUN sudo apt-get install postgresql postgresql-contrib
RUN sudo -i -u postgres

## step 5: create database account
RUN sudo su postgres
RUN cd
RUN create -s odoo
RUN exit

## step 6: create odoo user and odoo group
RUN sudo adduser --system --home=/opt/odoo --group odoo

## step 7: install Gdata
RUN cd /opt/odoo
RUN sudo wget https://pypi.python.org/packages/a8/70/bd554151443fe9e89d9a934a7891aaffc63b9cb5c7d608972919a002c03c/gdata-2.0.18.tar.gz
RUN sudo tar zxvf gdata-2.0.18.tar.gz
RUN sudo chown -R odoo: gdata-2.0.18
RUN sudo -s
RUN cd gdata-2.0.18/
RUN python setup.py install
RUN exit

## step 8: download odoo 10 from github
RUN cd /opt/odoo
RUN sudo wget https://github.com/odoo/odoo/archive/10.0.zip
RUN sudo unzip 10.0.zip
RUN sudo chown -R odoo: odoo-10.0

## step 9: create odoo log file
RUN sudo mkdir /var/log/odoo
RUN sudo chown -R odoo:root /var/log/odoo

## step 10: edit file config in docker compose

## step 11: setup WKHTMLTOPDF
RUN sudo wget https://downloads.wkhtmltopdf.org/0.12/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
RUN sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb
RUN sudo cp /usr/local/bin/wkhtmltoimage /usr/bin/wkhtmltoimage
RUN sudo cp /usr/local/bin/wkhtmltopdf /usr/bin/wkhtmltopdf

## step 12: start odoo
RUN cd /opt/odoo/odoo-10.0/
CMD ["./odoo-bin -c /etc/odoo.conf"]

## MANUAL: set password for odoo user