version: ${DOCKER_VERSION}

networks:
  default:
    name: ${NETWORK_NAME}

services:
  sc_mysql:
    image: ${MYSQL_VERSION}
    restart: unless-stopped
    container_name: ct_mysql
    ports:
      - ${MYSQL_PORT}:3306
      - ${MYSQL_XPORT}:33060
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      # - MYSQL_DATABASE=${MYSQL_DATABASE}
      # - MYSQL_USER=${MYSQL_USER}
      # - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
     - ${MYSQL_PATH}:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
