version: ${DOCKER_VERSION}

networks:
  default:
    name: ${NETWORK_NAME}

services:
  sc_redis:
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    container_name: ct_redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_PATH}:/data
